### ISSUE TITLE
ls /dev/trig1 produces no such file message

### ISSUE THREAD

**Issue by llorban** [strawlab/triggerbox#6]
I am not sure that the trig1 name is correctly set. All the preceding lines seem to work but running ls /dev/trig1 produces no file found message. 

```
sudo arduino-udev-name --set-name trig1 --verbose /dev/ttyACM0 
[sudo] password for flightlab: 
RAW:  0x4E 0x3D 0x74 0x72 0x69 0x67 0x31 0x0 0x0 0x0 0x44 0x42
SET NAME: trig1 (0x74 0x72 0x69 0x67 0x31)
```

```
sudo udevadm control --reload-rules
sudo udevadm trigger --attr-match=subsystem=tty
```
generates no output

```
ls /dev/trig1
ls: cannot access '/dev/trig1': No such file or directory
```

**Comment by llorban** [comment]
This is still an issue. One difference between the instructions and what I am seeing is that the Arduino appears on `/dev/ttyACM0` instead of `/dev/ttyUSB0`

**Comment by astraw** [comment]
I just added a troubleshooting section to the README in bc533ae6bcb4d386439ffe348562e8cc70b54db5. Also, in the `arduino-udev` package, I added support for another Arduino clone. Together, I think these will solve your problem and make it easier to debug similar such problems in the future. Thanks for the report.
